### ISSUE TITLE
Anonymous mailing telemetry

### ISSUE THREAD

**Issue by alexfarrill** [sofn-xyz/mailing#143]
To improve mailing and understand how people want to use it, let’s add telemetry. This way we can prioritize future development against real use cases. We’ll keep the telemetry anonymous by not associating it with an email.  We'll plan for:
- CLI command usage
- sendMail count

The solution will be anonymous -- no email necessary and not associated with an email

## Implementation

- Generate a random string called anonymousId to use for telemetry
- Store anonymousId in mailing config
- Add it to existing mailing config when you init or preview
- You can opt out by setting it to null, If the key is set to anything, including “null,” we won't overwrite it

**Comment by alexfarrill** [comment]
# Todo

## p0: get telemetry working in sendMail
- path forward for getting anonymousId into core repo

## p1: build step injection
- [ ] add api key to build from process.env

## p2: Config file stuff
- [ ] it should add to existing mail config

## p2: finalize
- [ ] document "null" feature for anonymousId
- [ ] do we need to call `client.shutdown`?  espc check use case of running init --quiet
**tests**
- [ ] config file stuff - new, existing, don't overwrite null
- [ ] it calls analytics
- [ ] e2e tests should not call telemetry

**Comment by alexfarrill** [comment]
Note: one additional consequence of not having mailing.config.js in mailing-core is we don't know the port the preview server is running on so we guess 3883.  I think this is the last place we have the hardcoded value

**Comment by alexfarrill** [comment]
Closed by #148
